#!/bin/sh
# Initial script for Linux Live Kit
# Author: Tomas M <http://www.linux-live.org/>

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/config
. /lib/livekitlib

transfer_initramfs

MEMORY=/m
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/b
ENCRYPTFS=$DATAMNT/encryptfs
HOME_ENCRYPTFS=$DATAMNT/home_encryptfs
SAVEDIR_ENCRYPTFS=$DATAMNT/savedir/savedir_encryptfs


header "Live Kit init <http://www.linux-live.org/>"


# load some modules manually first, then modprobe everything we have
# modprobe all devices excluding network drivers
modprobe_everything -v /drivers/net/

init_proc_sysfs

debug_start
debug_shell

#modprobe usb-storage quirks=152d:0562:u

init_devs
init_aufs
init_zram

init_devs

# initialize blkid cache file
init_blkid_cache

debug_shell
if [[ -d /ventoy ]]
then
    # init_devs must be executed again, otherwise disk devices are not available yet
    # But these are required for the ventoy disk mount hook
    . /ventoy/hook/ventoy-hook-lib.sh
    while [[ $(get_ventoy_disk_name) == "unknown" ]]
    do
        init_devs
    done
    VENTOY_DEVICE="$(blkid -s LABEL | grep 'LABEL="Ventoy"' | sed 's|:.*||g')"
    echo "ventoy_device should be here : $VENTOY_DEVICE"
    if [ "$VENTOY_DEVICE" != "" ]; then
       [ -d $DATAMNT ] || mkdir -p $DATAMNT
       mount $VENTOY_DEVICE $DATAMNT
       FROM="$(cmdline_value from)"
       if [ "$FROM" != "" ]; then
          DATA="$DATAMNT/$FROM"
       else
          DATA="$DATAMNT/$LIVEKITNAME"
       fi
    fi
else
    # find data dir with filesystem bundles
    DATA="$(find_data 45 "$DATAMNT")"
fi

check_data_found "$DATA"
debug_shell
# setup persistent changes, if possible
persistent_changes "$DATAMNT" "$CHANGES" "$ENCRYPTFS"
debug_shell
# copy to RAM if needed
DATA="$(copy_to_ram "$DATA" "$CHANGES")"

# mount bundles
mount_bundles "$DATA" "$BUNDLES"
debug_shell

if [ ! -z "$modpath" -a -z "$encryptfsmodpath" ]; then
	if [ -d "$DATAMNT"/"$modpath" ]; then
		mount_bundles_modpath "$DATAMNT"/"$modpath" "$BUNDLES"
	fi
fi

if [ ! -z "$encryptfsmodpath" -a -z "$modpath" ]; then
	if [ -d "$DATAMNT/$encryptfsmodpath" ]; then
      if [ -f "$DATAMNT/$encryptfsmodpath/gocryptfs.conf" -a -f "$DATAMNT/$encryptfsmodpath/gocryptfs.diriv" ]; then
			[ -d "$MEMORY/modpath" ] || mkdir -p "$MEMORY/modpath"
			if [ -f /passfile.txt ]; then
				gocryptfs --force_owner 0:0 -passfile /passfile.txt -nonempty -serialize_reads -allow_other "$DATAMNT/$encryptfsmodpath" "$MEMORY/modpath"
			else
				gocryptfs --force_owner 0:0 -nonempty -serialize_reads -allow_other "$DATAMNT/$encryptfsmodpath" "$MEMORY/modpath"
			fi
	  else
			echo "No gocryptfs.conf/gocryptfs.diriv file"
	  fi
	  mount_bundles_modpath "$MEMORY/modpath" "$BUNDLES"
	fi
fi


debug_shell

# init aufs union, or setup overlayfs union
init_union "$CHANGES" "$UNION" "$BUNDLES"

# add data to aufs union
union_append_bundles "$BUNDLES" "$UNION"

debug_shell
hostname="$(cat /proc/cmdline | grep hostname= | sed 's|.*hostname=||g' | sed 's| .*||g')"

if [ ! -z "$hostname" ]; then
echo "* Change hostname to $hostname"
# Configure hostname and network:
#echo "${hostname}.example.net" > ${UNION}/etc/HOSTNAME
echo "${hostname}" > ${UNION}/etc/hostname
if [ -f ${UNION}/etc/NetworkManager/NetworkManager.conf ]; then
  sed -i ${UNION}/etc/NetworkManager/NetworkManager.conf -e "s/^hostname=.*/hostname=${hostname}/"
fi
echo "127.0.0.1 localhost" > ${UNION}/etc/hosts
echo "::1 localhost ip6-localhost ip6-loopback" >> ${UNION}/etc/hosts
echo "ff02::1 ip6-allnodes" >> ${UNION}/etc/hosts
echo "ff02::2 ipt-allrouters" >> ${UNION}/etc/hosts
echo "127.0.0.1 ${hostname}.example.net ${hostname}" >> ${UNION}/etc/hosts
fi

debug_shell
#mount bind a $DATAMNT/$home folder to make it easier to update
#ex home=folder then the folder mount bind $DATAMNT/folder
#only mount 
if [ ! -z "$home" -a -z "$homedat" -a -z "$home_encryptfs" ]; then
	[ -d $DATAMNT/$home ] || mkdir -p $DATAMNT/$home
	if [ -d $DATAMNT/$home ]; then
		mount -o bind $DATAMNT/$home $UNION/home
	fi
fi

home_dat "$DATAMNT" "$UNION"

debug_shell

# this is for when you use ext4 or (posix-compible filesystem) to just mount bind the $DATAMNT/savedir/$savedir 
if [ ! -z "$savedir" -a -z "$savedirdat" -a -z "$savedir_encryptfs" ]; then
	[ -d $DATAMNT/savedir/$savedir ] || mkdir -p $DATAMNT/savedir/$savedir
	if [ -d $DATAMNT/savedir/$savedir ]; then
		[ -d $UNION/$savedir ] || mkdir -p $UNION/$savedir
		[ -d $CHANGES/.rootfs/$savedir ] || mkdir -p $CHANGES/.rootfs/$savedir
		[ -d $DATAMNT/savedir/$savedir/.savedir ] || mkdir -p $DATAMNT/savedir/$savedir/.savedir
		[ -d $DATAMNT/savedir/$savedir/.work ] || mkdir -p $DATAMNT/savedir/$savedir/.work
		mount -t overlay overlay -o lowerdir=$UNION/$savedir,upperdir=$DATAMNT/savedir/$savedir/.savedir,workdir=$DATAMNT/savedir/$savedir/.work $UNION/$savedir
	fi
fi

savedir_dat "$DATAMNT/savedir/${savedir}-dat-mount" "$DATAMNT/savedir/${savedir}-dat" "$DATAMNT/savedir/${savedir}"


if [ ! -z "$savedir" -a ! -z "$savedirdat" ]; then
	[ -d $DATAMNT/savedir/$savedir ] || mkdir -p $DATAMNT/savedir/$savedir
	if [ -d $DATAMNT/savedir/$savedir ]; then
		[ -d $UNION/$savedir ] || mkdir -p $UNION/$savedir
		[ -d $CHANGES/.rootfs/$savedir ] || mkdir -p $CHANGES/.rootfs/$savedir
		[ -d $DATAMNT/savedir/$savedir/.savedir ] || mkdir -p $DATAMNT/savedir/$savedir/.savedir
		[ -d $DATAMNT/savedir/$savedir/.work ] || mkdir -p $DATAMNT/savedir/$savedir/.work
		mount -t overlay overlay -o lowerdir=$UNION/$savedir,upperdir=$DATAMNT/savedir/$savedir/.savedir,workdir=$DATAMNT/savedir/$savedir/.work $UNION/$savedir
	fi
fi


debug_shell

#setup user and password
if [ ! -z "$user" ]; then
	if [ ! -d $UNION/home/$user ]; then
		[ -d $UNION/home ] || mkdir -p $UNION/home
		echo "Setting up $user"
		#chroot $UNION /usr/sbin/useradd -m -g users -s /bin/bash $user
		#chroot $UNION /usr/sbin/usermod -G wheel,audio,cdrom,floppy,plugdev,video,power,netdev,lp,scanner,kmem $user
		chroot $UNION useradd -m -g users -s /bin/bash $user
		chroot $UNION useradd -m -g users -s /bin/bash $user
		chroot $UNION usermod -G audio,cdrom,floppy,plugdev,video,netdev,lp,kmem,sudo $user
		#if this is added with kali linux it would fail the all groups so best to do it by itself
		chroot $UNION usermod -a -G scanner $user
		debug_shell
		echo "Setting up /home/$user folder"
		chroot $UNION mkhomedir_helper $user
		echo "Setting up $user password"
		echo "$user:$user" > $UNION/tmp/chpasswd.tmp
		#chroot $UNION /usr/sbin/chpasswd < $UNION/tmp/chpasswd.tmp
		chroot $UNION chpasswd < $UNION/tmp/chpasswd.tmp
		debug_shell
		
		rm -f $UNION/tmp/chpasswd.tmp
		# Configure suauth:
		#echo "Configure suauth"
		#echo "root:${user}:OWNPASS" > ${UNION}/etc/suauth
		#echo "root:ALL EXCEPT GROUP users:DENY" >> ${UNION}/etc/suauth
		#chmod 600 ${UNION}/etc/suauth

		# Configure sudoers:
		#echo "Configure sudoers"
		#chmod 640 ${UNION}/etc/sudoers
		#sed -i ${UNION}/etc/sudoers -e 's/# *\(%users\sALL=(ALL)\sALL\)/\1/'
		#chmod 440 ${UNION}/etc/sudoers
	else
		echo "/home/$user folder exists."
	fi
fi
debug_shell

#copy the password files to /tmp1 if $home is used
if [ ! -z "$home" -a  ! -z "$user" -a "$(cat /proc/cmdline | grep perch)" == "" ]; then
	for file in group gshadow passwd shadow subgid subuid; do
		[ -d /tmp1/etc ] || mkdir -p /tmp1/etc
		if [ -f "$CHANGES/.rootfs/etc/$file" ]; then
				file1="$CHANGES/.rootfs/etc/$file"
		elif [ -f "$CHANGES/etc/$file" ]; then
				file1="$CHANGES/etc/$file"
		fi
		if [ -f "${file1}" ]; then
			echo "${file1}"
			cp -a "${file1}" /tmp1/etc/$file
		fi
	done
	date="$(date +%Y%m%d-%H%M%S)"
	modulepsw="$DATA/modules/${date}-100-${user}-password.sb"
	if [ "$(find $DATA/modules -name "*-100-${user}-password.sb" -type f)" == "" ]; then
		echo "Making $modulepsw"
		mksquashfs /tmp1 $modulepsw 2>/dev/null >>/var/log/livedbg
	fi
fi
debug_shell

if [ ! -z "$autologin" ]; then
	echo "setting up lightdm autologin of user $user"
	if [ -d $UNION/etc/lightdm/lightdm.conf.d ]; then
		echo "[Seat:*]" > $UNION/etc/lightdm/lightdm.conf.d/01_${user}.conf
		echo "autologin-user=$user" >> $UNION/etc/lightdm/lightdm.conf.d/01_${user}.conf
		echo "autologin-user-timeout=0" >> $UNION/etc/lightdm/lightdm.conf.d/01_${user}.conf
	fi
	echo "[Autologin]" > $UNION/etc/sddm.conf
	echo "Session=Lubuntu" >> $UNION/etc/sddm.conf
	echo "User=$user" >> $UNION/etc/sddm.conf
fi

debug_shell
#timezone
if [ ! -z "$timezone" ]; then
	if [ -f $UNION/usr/share/zoneinfo/$timezone ]; then
		echo "Timezone $timezone"
		ln -sf /usr/share/zoneinfo/$timezone $UNION/etc/localtime
		echo "$timezone" > $UNION/etc/timezone
	fi
fi
debug_shell

if [ ! -z "$locale" ]; then
	echo "Locale ${locale}.UTF-8"
	sed -i 's|^LC_ALL=.*||g' $UNION/etc/environment
	echo "LC_ALL=${locale}.UTF-8" | tee -a $UNION/etc/environment
	echo "${locale}.UTF-8 UTF-8" | tee $UNION/etc/locale.gen
	echo "LANG=${locale}.UTF-8" | tee $UNION/etc/locale.conf
	echo "chroot $UNION locale-gen ${locale}.UTF-8"
	chroot $UNION locale-gen ${locale}.UTF-8
fi
debug_shell
if [ ! -z "$keyboard" ]; then
	echo "setting keyboard to $keyboard"
	chroot $UNION localectl set-keymap "$keyboard"
fi

if [ -d /ventoy ]; then
	if [ ! -f $CHANGES/.ventoyignore ]; then
		touch $CHANGES/.ventoyignore
	fi
	if [ ! -f $DATAMNT/$home/.ventoyignore ]; then
		touch $DATAMNT/$home/.ventoyignore
	fi
	if [ ! -f $DATAMNT/savedir/.ventoyignore ]; then
		touch $DATAMNT/savedir/.ventoyignore
	fi
fi

debug_shell
# rootcopy
if [ -z "$norootcopy" ]; then
	copy_rootcopy_content "$DATA" "$UNION"
fi
debug_shell
# create fstab
fstab_create "$UNION" "$DATAMNT"
debug_shell
header "Live Kit done, starting $LIVEKITNAME"
change_root "$UNION"

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
