#!/bin/sh
# Initial script for Linux Live Kit
# Author: Tomas M <http://www.linux-live.org/>

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/config
. /lib/livekitlib

transfer_initramfs

MEMORY=/m
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/b
ENCRYPTFS=$DATAMNT/encryptfs
HOME_ENCRYPTFS=$DATAMNT/home_encryptfs
SAVEDIR_ENCRYPTFS=$DATAMNT/savedir/savedir_encryptfs


header "Live Kit init <http://www.linux-live.org/>"


# load some modules manually first, then modprobe everything we have
# modprobe all devices excluding network drivers
modprobe_everything -v /drivers/net/

init_proc_sysfs

debug_start
debug_shell

#modprobe usb-storage quirks=152d:0562:u

init_devs
init_aufs
init_zram

init_devs

# initialize blkid cache file
init_blkid_cache

debug_shell
if [[ -d /ventoy ]]
then
    # init_devs must be executed again, otherwise disk devices are not available yet
    # But these are required for the ventoy disk mount hook
    . /ventoy/hook/ventoy-hook-lib.sh
    while [[ $(get_ventoy_disk_name) == "unknown" ]]
    do
        init_devs
    done
    VENTOY_DEVICE="$(blkid -s LABEL | grep 'LABEL="Ventoy"' | sed 's|:.*||g')"
    echo "ventoy_device should be here : $VENTOY_DEVICE"
    if [ "$VENTOY_DEVICE" != "" ]; then
       [ -d $DATAMNT ] || mkdir -p $DATAMNT
       mount $VENTOY_DEVICE $DATAMNT
       FROM="$(cmdline_value from)"
       if [ "$FROM" != "" ]; then
          DATA="$DATAMNT/$FROM"
       else
          DATA="$DATAMNT/$LIVEKITNAME"
       fi
    fi
else
    # find data dir with filesystem bundles
    DATA="$(find_data 45 "$DATAMNT")"
fi

check_data_found "$DATA"
debug_shell
# setup persistent changes, if possible
persistent_changes "$DATAMNT" "$CHANGES" "$ENCRYPTFS"
debug_shell
# copy to RAM if needed
DATA="$(copy_to_ram "$DATA" "$CHANGES")"

# mount bundles
mount_bundles "$DATA" "$BUNDLES"
debug_shell

if [ ! -z "$modpath" -a -z "$encryptfsmodpath" ]; then
	if [ -d "$DATAMNT"/"$modpath" ]; then
		mount_bundles_modpath "$DATAMNT"/"$modpath" "$BUNDLES"
	fi
fi

if [ ! -z "$encryptfsmodpath" -a -z "$modpath" ]; then
	if [ -d "$DATAMNT/$encryptfsmodpath" ]; then
      if [ -f "$DATAMNT/$encryptfsmodpath/gocryptfs.conf" -a -f "$DATAMNT/$encryptfsmodpath/gocryptfs.diriv" ]; then
			[ -d "$MEMORY/modpath" ] || mkdir -p "$MEMORY/modpath"
			if [ -f /passfile.txt ]; then
				gocryptfs --force_owner 0:0 -passfile /passfile.txt -nonempty -serialize_reads -allow_other "$DATAMNT/$encryptfsmodpath" "$MEMORY/modpath"
			else
				gocryptfs --force_owner 0:0 -nonempty -serialize_reads -allow_other "$DATAMNT/$encryptfsmodpath" "$MEMORY/modpath"
			fi
	  else
			echo "No gocryptfs.conf/gocryptfs.diriv file"
	  fi
	  mount_bundles_modpath "$MEMORY/modpath" "$BUNDLES"
	fi
fi


debug_shell

# init aufs union, or setup overlayfs union
init_union "$CHANGES" "$UNION" "$BUNDLES"

# add data to aufs union
union_append_bundles "$BUNDLES" "$UNION"

debug_shell

setup_hostname "$UNION"

debug_shell
#mount bind a $DATAMNT/$home folder to make it easier to update
#ex home=folder then the folder mount bind $DATAMNT/folder
#only mount 
if [ ! -z "$home" -a -z "$homedat" -a -z "$home_encryptfs" ]; then
	[ -d $DATAMNT/$home ] || mkdir -p $DATAMNT/$home
	if [ -d $DATAMNT/$home ]; then
		mount -o bind $DATAMNT/$home $UNION/home
	fi
fi

home_dat "$DATAMNT" "$UNION"

debug_shell

# this is for when you use ext4 or (posix-compible filesystem) to just mount bind the $DATAMNT/savedir/$savedir 
if [ ! -z "$savedir" -a -z "$savedirdat" -a -z "$savedir_encryptfs" ]; then
	[ -d $DATAMNT/savedir/$savedir ] || mkdir -p $DATAMNT/savedir/$savedir
	if [ -d $DATAMNT/savedir/$savedir ]; then
		[ -d $UNION/$savedir ] || mkdir -p $UNION/$savedir
		[ -d $CHANGES/.rootfs/$savedir ] || mkdir -p $CHANGES/.rootfs/$savedir
		[ -d $DATAMNT/savedir/$savedir/.savedir ] || mkdir -p $DATAMNT/savedir/$savedir/.savedir
		[ -d $DATAMNT/savedir/$savedir/.work ] || mkdir -p $DATAMNT/savedir/$savedir/.work
		mount -t overlay overlay -o lowerdir=$UNION/$savedir,upperdir=$DATAMNT/savedir/$savedir/.savedir,workdir=$DATAMNT/savedir/$savedir/.work $UNION/$savedir
	fi
fi

savedir_dat "$DATAMNT/savedir/${savedir}-dat-mount" "$DATAMNT/savedir/${savedir}-dat" "$DATAMNT/savedir/${savedir}"


if [ ! -z "$savedir" -a ! -z "$savedirdat" ]; then
	[ -d $DATAMNT/savedir/$savedir ] || mkdir -p $DATAMNT/savedir/$savedir
	if [ -d $DATAMNT/savedir/$savedir ]; then
		[ -d $UNION/$savedir ] || mkdir -p $UNION/$savedir
		[ -d $CHANGES/.rootfs/$savedir ] || mkdir -p $CHANGES/.rootfs/$savedir
		[ -d $DATAMNT/savedir/$savedir/.savedir ] || mkdir -p $DATAMNT/savedir/$savedir/.savedir
		[ -d $DATAMNT/savedir/$savedir/.work ] || mkdir -p $DATAMNT/savedir/$savedir/.work
		mount -t overlay overlay -o lowerdir=$UNION/$savedir,upperdir=$DATAMNT/savedir/$savedir/.savedir,workdir=$DATAMNT/savedir/$savedir/.work $UNION/$savedir
	fi
fi


debug_shell

setup_homeuser "$user" "$UNION"

debug_shell

if [ ! -z "$desktop" ]; then
   setup_desktop "$desktop" "$UNION"
fi

debug_shell

if [ ! -z "$rootpw" ]; then
   echo "Setting up root password : $rootpw"
   echo "root:$rootpw" > $UNION/tmp/chpasswd.tmp
   chroot $UNION chpasswd < $UNION/tmp/chpasswd.tmp
   rm $UNION/tmp/chpasswd.tmp
fi

debug_shell

#copy the password files to /tmp1 if $home is used
if [ ! -z "$home" -a  ! -z "$user" -a "$(cat /proc/cmdline | grep perch)" == "" ]; then
	for file in group gshadow passwd shadow subgid subuid; do
		[ -d /tmp1/etc ] || mkdir -p /tmp1/etc
		if [ -f "$CHANGES/.rootfs/etc/$file" ]; then
				file1="$CHANGES/.rootfs/etc/$file"
		elif [ -f "$CHANGES/etc/$file" ]; then
				file1="$CHANGES/etc/$file"
		fi
		if [ -f "${file1}" ]; then
			echo "${file1}"
			cp -a "${file1}" /tmp1/etc/$file
		fi
		[ -d /tmp1/etc/sudoers.d ] || mkdir -p /tmp1/etc/sudoers.d
		echo "${user} ALL=(ALL) ALL" > /tmp1/etc/sudoers.d/$user
		chmod 0440 /tmp1/etc/sudoers.d/$user
	done
	date="$(date +%Y%m%d-%H%M%S)"
	modulepsw="$DATA/modules/${date}-100-${user}-password.sb"
	if [ "$(find $DATA/modules -name "*-100-${user}-password.sb" -type f)" == "" ]; then
		echo "Making $modulepsw"
		mksquashfs /tmp1 $modulepsw 2>/dev/null >>/var/log/livedbg
	fi
fi
debug_shell

if [ ! -z "$autologin" ]; then
	setup_autologin "$user" "$UNION"
	if [ ! -z "$desktop" ]; then
		if [ -f $UNION/etc/sddm.conf.d/01_${user}.conf ]; then
			sed -i 's|^Session=.*||g' $UNION/etc/sddm.conf.d/01_${user}.conf
			if [ "$desktop" == "lxqt" ]; then
				if [ -f $UNION/usr/share/xsessions/Lubuntu.desktop ]; then
					echo "Session=Lubuntu" >> $UNION/etc/sddm.conf.d/01_${user}.conf
				elif [ -f $UNION/usr/share/xsessions/lxqt.desktop ]; then
					echo "Session=lxqt" >> $UNION/etc/sddm.conf.d/01_${user}.conf
				fi
			elif [ "$desktop" == "icewm" ]; then
				echo "Session=icewm-session" >> $UNION/etc/sddm.conf.d/01_${user}.conf
			elif [ "$desktop" == "lxde" ]; then
				echo "Session=LXDE" >> $UNION/etc/sddm.conf.d/01_${user}.conf
			elif [ "$desktop" == "budgie" ]; then
				echo "Session=budgie-desktop" >> $UNION/etc/sddm.conf.d/01_${user}.conf
			elif [ "$desktop" == "kde" ]; then
				echo "Session=plasmax11" >> $UNION/etc/sddm.conf.d/01_${user}.conf
			else
				echo "Session=$desktop" >> $UNION/etc/sddm.conf.d/01_${user}.conf
			fi
		fi
	fi
fi

debug_shell

setup_timezone "$timezone" "$UNION"

debug_shell

setup_locale "$locale" "$UNION"

debug_shell

setup_keyboard "$keyboard" "$UNION"

if [ -d /ventoy ]; then
	if [ ! -f $CHANGES/.ventoyignore ]; then
		touch $CHANGES/.ventoyignore
	fi
	if [ ! -f $DATAMNT/$home/.ventoyignore ]; then
		touch $DATAMNT/$home/.ventoyignore
	fi
	if [ ! -f $DATAMNT/savedir/.ventoyignore ]; then
		touch $DATAMNT/savedir/.ventoyignore
	fi
fi

debug_shell
# rootcopy
if [ -z "$norootcopy" ]; then
	copy_rootcopy_content "$DATA" "$UNION"
fi
debug_shell
# create fstab
fstab_create "$UNION" "$DATAMNT"
debug_shell
header "Live Kit done, starting $LIVEKITNAME"
change_root "$UNION"

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
